### ISSUE TITLE
Variable support

### ISSUE THREAD

**Issue by shvelo** [Kirkhammetz/termly.js#2]
It would be nice to have shell variable support, maybe even predefined environment variables

**Comment by simonecorsi** [comment]
Cool that sound useful! 
I'll play with it this weekend, maybe a simple key value pair that you can add at instantiation and an export command to add others.
For predefined variables, intended as coming bundled with it, it's so basic for now I don't even know what variables it could have! Since it depend on the use cases someone does with it I think adding the capability to pass an env object at instantiation and a builtin command to add them could become useful

**Comment by simonecorsi** [comment]
Thank you for the idea :)

Docs at http://termlyjs.info/#/#environment-variables
